language: cpp
compiler: clang
cache: ccache
before_script:
  - cmake --version
  - qmake --version
  - $CXX --version
  - $CC --version
script:
  - mkdir build && cd build
  - find / -name 'libQt*' || true
  # qt5.2.1 _qt5_OpenGL_check_file_exists fails without this
  - ln -s /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.2.1 /usr/lib/x86_64-linux-gnu/libQtOpenGL.so
  - cmake -DCUDA_HOST_COMPILER="$(which gcc)" ..
  - make -j3

addons:
  apt:
    packages:
      - cmake # >= 3.1
      # Qt >= 5.5.0
      - qt5-default
      # Boost >= 1.54.0
      - libboost-atomic-dev
      - libboost-chrono-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-thread-dev
      # Python 2.7
      - python2.7-dev
      - python-numpy
      - python-scipy
      # Additional libs
      - libpng-dev
      - zlib1g-dev
      - libglew-dev
      - freeglut3-dev

# Fails fast
before_install: set -e
after_script: set +e
