language: cpp
compiler:
  - clang # >= 3.4
# - gcc # >= 4.8
cache: ccache
before_script:
  - cmake --version
  - qmake --version
  - ninja --version
  - $CXX --version
  - $CC --version
script:
  - mkdir build && cd build
  - cmake -GNinja -DCUDA_HOST_COMPILER="$(which gcc)" ..
  - ninja

addons:
  apt:
    packages:
      - cmake # >= 3.1
      - ninja-build
      # Qt >= 5.5.0
      - qt5-default
      - libqt5opengl5
      - libqt5opengl5-dev
      # Boost >= 1.54.0
      - libboost-atomic-dev
      - libboost-chrono-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-locale-dev
      - libboost-regex-dev
      - libboost-system-dev
      - libboost-thread-dev
      # Python 2.7
      - python2.7-dev
      - python-numpy
      - python-scipy
      # Additional libs
      - libpng-dev
      - zlib1g-dev
      - libglew-dev
      - freeglut3-dev

# Fails fast
before_install: set -e
after_script: set +e
